FROM node:16-alpine

WORKDIR /app

# Install dependencies for nuclei
RUN apk add --no-cache ca-certificates git

# Copy package.json and package-lock.json
COPY server/package*.json ./

# Install dependencies
RUN npm install

# Copy server files
COPY server ./

# Expose port
EXPOSE 5000

# Start server
CMD ["npm", "start"]