FROM node:16-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY client/package*.json ./

# Install dependencies
RUN npm install

# Copy client files
COPY client ./

# Fix permissions issue for node_modules/.cache
RUN mkdir -p /app/node_modules/.cache && chmod -R 777 /app/node_modules/.cache

# Expose port
EXPOSE 3000

# Start client
CMD ["npm", "start"]